project:
  type: website

website:
  title: "The Pond"
  navbar:
    logo: images/FROGSlogo.jpg
    logo-alt: "FROGS"
    left:
      - href: index.qmd
        text: Home
      - href: shallows/index.qmd
        text: The Shallows
      - href: lilypads/index.qmd
        text: LilyPads
      - href: deep-water/index.qmd
        text: Deep Water
      - href: spring/index.qmd
        text: The Spring
      - href: about.qmd
        text: About
  page-footer: "The Pond is part of [FROGS](https://linked.earth/FROGS/), a [LinkedEarth](https://linked.earth/) project."

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



